version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-cff:
    docker:
      - image: 'cypress/browsers:node12.14.1-chrome83-ff77'
workflows:
  build:
    jobs:
      - cypress/run:
          name: 'Chrome'
          executor: with-cff
          browser: chrome
      - cypress/run:
          name: 'Firefox'
          executor: with-cff
          browser: firefox
